spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/shoe_store}
    username: ${DB_USERNAME:shoe_store}
    password: ${DB_PASSWORD:ShoeStore@2026}
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: ShoeStoreLocalPool
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    com.shoestore: DEBUG
    org.hibernate.SQL: DEBUG
